const faq_data = [
    {id:0, que:' Why is the Helpdesk closed?', ans:'Because of the COVID-19 Pandemic.', category:'' },
    {id:0, que:' Why is the Helpdesk closed?', ans:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Necessitatibus fuga, illo, repellendus quisquam aliquid rem ipsa quos sequi nostrum ratione magni molestiae? Tenetur voluptate quod in dolores, corrupti adipisci ab rem aperiam earum nobis cum vel distinctio optio nulla repellat minus obcaecati enim blanditiis ipsum dolor vitae voluptatum inventore. Reiciendis.', category:'' }, 
    {id:0, que:' Why is the Helpdesk closed?', ans:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Necessitatibus fuga, illo, repellendus quisquam aliquid rem ipsa quos sequi nostrum ratione magni molestiae? Tenetur voluptate quod in dolores, corrupti adipisci ab rem aperiam earum nobis cum vel distinctio optio nulla repellat minus obcaecati enim blanditiis ipsum dolor vitae voluptatum inventore. Reiciendis.', category:'' }, 
    {id:0, que:' Why is the Helpdesk closed?', ans:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Necessitatibus fuga, illo, repellendus quisquam aliquid rem ipsa quos sequi nostrum ratione magni molestiae? Tenetur voluptate quod in dolores, corrupti adipisci ab rem aperiam earum nobis cum vel distinctio optio nulla repellat minus obcaecati enim blanditiis ipsum dolor vitae voluptatum inventore. Reiciendis.', category:'' }, 
    {id:0, que:' Why is the Helpdesk closed?', ans:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Necessitatibus fuga, illo, repellendus quisquam aliquid rem ipsa quos sequi nostrum ratione magni molestiae? Tenetur voluptate quod in dolores, corrupti adipisci ab rem aperiam earum nobis cum vel distinctio optio nulla repellat minus obcaecati enim blanditiis ipsum dolor vitae voluptatum inventore. Reiciendis.', category:'' }, 
    {id:0, que:' Why is the Helpdesk closed?', ans:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Necessitatibus fuga, illo, repellendus quisquam aliquid rem ipsa quos sequi nostrum ratione magni molestiae? Tenetur voluptate quod in dolores, corrupti adipisci ab rem aperiam earum nobis cum vel distinctio optio nulla repellat minus obcaecati enim blanditiis ipsum dolor vitae voluptatum inventore. Reiciendis.', category:'' }, 
    {id:0, que:' Why is the Helpdesk closed?', ans:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Necessitatibus fuga, illo, repellendus quisquam aliquid rem ipsa quos sequi nostrum ratione magni molestiae? Tenetur voluptate quod in dolores, corrupti adipisci ab rem aperiam earum nobis cum vel distinctio optio nulla repellat minus obcaecati enim blanditiis ipsum dolor vitae voluptatum inventore. Reiciendis.', category:'' }, 
   
]


export default faq_data
